<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-4.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:th="http://www.thymeleaf.org">

<head th:substituteby="header :: copy"></head>

<!-- 
 This default page is designed to support several defaults:
 1. Error pages generated by Spring Boot's error configuration receive
      $timestamp, $status, $error, $message as variables - see
      org.springframework.boot.actuate.web.BasicErrorController
 2. By default, error pages setup by SimpleMappingExceptionResolver receive
      $exception
 3. We have configured our SimpleMappingExceptionResolver to setup $ex
      instead, just to show it can be done.
 -->
<body>
	<h1>Error Page</h1>
    <p>Application has encountered an error. Please contact support on ...</p>
    
    <!--
    Failed URL: ${url}
    Exception: ${exception}
    Exception message:  ${exception.message}
    <c:forEach items="${exception.stackTrace}" var="ste">    ${ste} 
    </c:forEach>
    -->

</body>
</html>